// GLSL source held as Kotlin string constants. v0.1 trades IDE syntax
// highlighting for the simplicity of zero asset-loading code; refactor to
// assets/shaders/*.frag if the count grows past ~6 or if external tooling
// (SPIRV-Cross, ShaderToy round-tripping) starts to matter.
//
// Shapes mirror the web GLSL in web-driver/effects/*.ts. Keep in sync manually.

package com.simiancraft.kaleidoscope.gpu

internal object Shaders {
    // Procedural full-screen quad via gl_VertexID; no VAO or VBO required.
    // Caller does: glDrawArrays(GL_TRIANGLE_STRIP, 0, 4).
    // gl_VertexID -> (p in 0..2 space) -> (clip in -1..1, uv in 0..1)
    //   0 -> (0,0) -> (-1,-1), uv (0,0)
    //   1 -> (2,0) -> ( 1,-1), uv (1,0)
    //   2 -> (0,2) -> (-1, 1), uv (0,1)
    //   3 -> (2,2) -> ( 1, 1), uv (1,1)
    // Canonical source: shaders/passthrough.vert. Generated into
    // ShadersGenerated by `bun run build:shaders`; delegated here so call sites
    // keep using Shaders.PASSTHROUGH_VERT.
    val PASSTHROUGH_VERT = ShadersGenerated.PASSTHROUGH_VERT

    // Sample the OES external camera texture and emit as 2D RGBA. The first
    // pass of every effect runs this so subsequent passes can use sampler2D.
    //
    // The camera's TextureBuffer carries a transform matrix that encodes the
    // selfie mirror (front cameras), sensor orientation correction, and any
    // crop. The renderer applies it when displaying the raw OES; we have to
    // apply it ourselves before sampling, otherwise our 2D output is the raw
    // sensor view instead of the screen-aligned view.
    const val OES_PASSTHROUGH_FRAG = """#version 300 es
#extension GL_OES_EGL_image_external_essl3 : require
precision mediump float;
uniform samplerExternalOES uTex;
uniform mat4 uTexMatrix;
in highp vec2 vUv;
out vec4 oColor;
void main() {
  vec4 transformed = uTexMatrix * vec4(vUv, 0.0, 1.0);
  oColor = texture(uTex, transformed.xy);
}
"""

    // Plain 2D-sampler passthrough. The RGB-input branch of an effect (i.e. when
    // it is chained AFTER another effect that already emitted a GL_TEXTURE_2D
    // TextureBuffer) runs this in place of OES_PASSTHROUGH_FRAG to land the
    // upstream 2D source in the cached "original 2D" FBO. No texture matrix: the
    // upstream effect already normalized orientation (display-upright, rotation
    // 0), so this is an identity copy. Platform-local (no OES, no cross-runtime
    // variant), so it stays hand-written here rather than in ShadersGenerated.
    const val TWO_D_PASSTHROUGH_FRAG = """#version 300 es
precision mediump float;
uniform sampler2D uTex;
in highp vec2 vUv;
out vec4 oColor;
void main() {
  oColor = texture(uTex, vUv);
}
"""

    // Composite compositor BLUR layer: camera-sampling separable gaussian, 13-tap
    // with sigma-coupled spread. Canonical source shaders/blur/composite-blur.frag,
    // generated into ShadersGenerated; delegated here. Migrated off the hand-written
    // LayerShaders.BLUR_FRAG (and the old CPU-kernel linear blur.frag, now deleted).
    val COMPOSITE_BLUR_FRAG = ShadersGenerated.COMPOSITE_BLUR_FRAG

    // Composite compositor CAMERA layer (direct/background): raw display-upright
    // camera, opaque. Canonical source shaders/_shared/composite-camera.frag,
    // generated into ShadersGenerated; delegated here. Migrated off the hand-written
    // LayerShaders.CAMERA_FRAG.
    val COMPOSITE_CAMERA_FRAG = ShadersGenerated.COMPOSITE_CAMERA_FRAG

    // Transform: a single-pass geometric reorientation (axis flip or 90-degree
    // rotation) driven by the uUvTransform mat2 the host computes from a pure
    // screen-space op via Orientation.mat2For. One shader serves all four ops
    // (flip-x, flip-y, rotate-cw, rotate-ccw); the input is already
    // display-upright (camera orientation is normalized once in Ingest), so no
    // rotation correction happens here.
    // Canonical source: shaders/transform.frag. Generated into ShadersGenerated
    // by `bun run build:shaders`; delegated here.
    val TRANSFORM_FRAG = ShadersGenerated.TRANSFORM_FRAG
}
