// GLSL source held as Kotlin string constants. v0.1 trades IDE syntax
// highlighting for the simplicity of zero asset-loading code; refactor to
// assets/shaders/*.frag if the count grows past ~6 or if external tooling
// (SPIRV-Cross, ShaderToy round-tripping) starts to matter.
//
// Shapes mirror the web GLSL in src/web/effects/*.ts. Keep in sync manually.

package com.simiancraft.kaleidoscope.gpu

internal object Shaders {
  // Procedural full-screen quad via gl_VertexID; no VAO or VBO required.
  // Caller does: glDrawArrays(GL_TRIANGLE_STRIP, 0, 4).
  // gl_VertexID -> (p in 0..2 space) -> (clip in -1..1, uv in 0..1)
  //   0 -> (0,0) -> (-1,-1), uv (0,0)
  //   1 -> (2,0) -> ( 1,-1), uv (1,0)
  //   2 -> (0,2) -> (-1, 1), uv (0,1)
  //   3 -> (2,2) -> ( 1, 1), uv (1,1)
  // Canonical source: shaders/passthrough.vert. Generated into
  // ShadersGenerated by `bun run build:shaders`; delegated here so call sites
  // keep using Shaders.PASSTHROUGH_VERT.
  val PASSTHROUGH_VERT = ShadersGenerated.PASSTHROUGH_VERT

  // Sample the OES external camera texture and emit as 2D RGBA. The first
  // pass of every effect runs this so subsequent passes can use sampler2D.
  //
  // The camera's TextureBuffer carries a transform matrix that encodes the
  // selfie mirror (front cameras), sensor orientation correction, and any
  // crop. The renderer applies it when displaying the raw OES; we have to
  // apply it ourselves before sampling, otherwise our 2D output is the raw
  // sensor view instead of the screen-aligned view.
  const val OES_PASSTHROUGH_FRAG = """#version 300 es
#extension GL_OES_EGL_image_external_essl3 : require
precision mediump float;
uniform samplerExternalOES uTex;
uniform mat4 uTexMatrix;
in highp vec2 vUv;
out vec4 oColor;
void main() {
  vec4 transformed = uTexMatrix * vec4(vUv, 0.0, 1.0);
  oColor = texture(uTex, transformed.xy);
}
"""

  // Plain 2D-sampler passthrough. The RGB-input branch of an effect (i.e. when
  // it is chained AFTER another effect that already emitted a GL_TEXTURE_2D
  // TextureBuffer) runs this in place of OES_PASSTHROUGH_FRAG to land the
  // upstream 2D source in the cached "original 2D" FBO. No texture matrix: the
  // upstream effect already normalized orientation (display-upright, rotation
  // 0), so this is an identity copy. Platform-local (no OES, no cross-runtime
  // variant), so it stays hand-written here rather than in ShadersGenerated.
  const val TWO_D_PASSTHROUGH_FRAG = """#version 300 es
precision mediump float;
uniform sampler2D uTex;
in highp vec2 vUv;
out vec4 oColor;
void main() {
  oColor = texture(uTex, vUv);
}
"""

  // Composite compositor BLUR layer: camera-sampling separable gaussian, 13-tap
  // with sigma-coupled spread. Canonical source shaders/blur/composite-blur.frag,
  // generated into ShadersGenerated; delegated here. Migrated off the hand-written
  // LayerShaders.BLUR_FRAG (and the old CPU-kernel linear blur.frag, now deleted).
  val COMPOSITE_BLUR_FRAG = ShadersGenerated.COMPOSITE_BLUR_FRAG

  // Composite compositor CAMERA layer (direct/background): raw display-upright
  // camera, opaque. Canonical source shaders/_shared/composite-camera.frag,
  // generated into ShadersGenerated; delegated here. Migrated off the hand-written
  // LayerShaders.CAMERA_FRAG.
  val COMPOSITE_CAMERA_FRAG = ShadersGenerated.COMPOSITE_CAMERA_FRAG

  // Composite: mix(background, original, mask). One shader, byte-identical
  // to src/web/shaders.ts's COMPOSITE_FRAG_SRC.
  //
  // uOriginal and uBackground are expected to land with semantic "top of
  // source image" at GL v=1; the shader samples both at vUv directly. On
  // Android the OES->2D pass with transformMatrix lands the original at
  // v=1, and the bg PNG is pre-flipped via Bitmap matrix before
  // GLUtils.texImage2D since Android OpenGL ES has no flipY flag.
  //
  // uMask is sampled at vUv * uMaskUvScale + uMaskUvOffset. On Android,
  // those are identity (1,1) and (0,0) because the readback round-trip
  // (glReadPixels bottom-up plus Bitmap top-down plus GLUtils.texImage2D
  // row-preserving) leaves the mask aligned with origFbo. On web they are
  // (1,-1) and (0,1) to encode a V-flip on the mask sampling, because
  // canvas-staging the mask there would mangle the soft confidence values
  // in alpha (premultiplied-alpha math).
  //
  // uMaskLo / uMaskHi parameterize the smoothstep transition over the raw
  // confidence map. The processor computes them from a maskHardness factor
  // (0 = soft halo, 1 = hard edge) so callers do not have to think in lo/hi
  // pairs.
  //
  // uBgUvScale and uBgUvOffset control how the background texture is mapped
  // onto the output. For blur, they are (1,1) and (0,0); sample the full
  // blurred copy. For an image layer, the caller computes them to perform
  // a cover-fit center crop so an arbitrarily-shaped image fills the output
  // without distortion.
  // Canonical source: shaders/composite.frag. Generated into ShadersGenerated
  // by `bun run build:shaders`; delegated here. The per-platform mask/bg
  // orientation differences live in the uniforms the host sets (see above),
  // not in the shader, so the same generated body serves every runtime.
  val COMPOSITE_FRAG = ShadersGenerated.COMPOSITE_FRAG

  // Transform: a single-pass geometric reorientation (axis flip or 90-degree
  // rotation) driven by the uUvTransform mat2 the host computes from a pure
  // screen-space op via Orientation.mat2For. One shader serves all four ops
  // (flip-x, flip-y, rotate-cw, rotate-ccw); the input is already
  // display-upright (camera orientation is normalized once in Ingest), so no
  // rotation correction happens here.
  // Canonical source: shaders/transform.frag. Generated into ShadersGenerated
  // by `bun run build:shaders`; delegated here.
  val TRANSFORM_FRAG = ShadersGenerated.TRANSFORM_FRAG
}
