// @generated by scripts/build-shaders.ts from shaders/. DO NOT EDIT.
// Run `bun run build:shaders` to regenerate.
//
// Cross-runtime shared shaders. Platform-local shaders (OES external texture,
// 2D passthrough) stay hand-written in Shaders.kt, which delegates the consts
// below.

package com.simiancraft.kaleidoscope.gpu

internal object ShadersGenerated {
  const val PASSTHROUGH_VERT = """#version 300 es
precision highp float;
out highp vec2 vUv;
void main() {
  vec2 p = vec2(float((gl_VertexID & 1) << 1), float(gl_VertexID & 2));
  vUv = p * 0.5;
  gl_Position = vec4(p - 1.0, 0.0, 1.0);
}
"""

  const val COMPOSITE_FRAG = """#version 300 es
precision mediump float;
uniform sampler2D uOriginal;
uniform sampler2D uBackground;
uniform sampler2D uMask;
uniform vec2 uBgUvScale;
uniform vec2 uBgUvOffset;
uniform vec2 uMaskUvScale;
uniform vec2 uMaskUvOffset;
uniform float uMaskLo;
uniform float uMaskHi;
in highp vec2 vUv;
out vec4 oColor;
void main() {
  vec2 maskUv = vUv * uMaskUvScale + uMaskUvOffset;
  float raw = texture(uMask, maskUv).r;
  float safeHi = max(uMaskHi, uMaskLo + 0.001);
  float m = smoothstep(uMaskLo, safeHi, raw);
  vec3 orig = texture(uOriginal, vUv).rgb;
  vec2 bgUv = clamp(vUv * uBgUvScale + uBgUvOffset, 0.0, 1.0);
  vec3 bg = texture(uBackground, bgUv).rgb;
  oColor = vec4(mix(bg, orig, m), 1.0);
}
"""

  const val COMPOSITE_CAMERA_FRAG = """#version 300 es
precision highp float;
uniform sampler2D uCamera;
in highp vec2 vUv;
out vec4 oColor;
void main() {
  oColor = vec4(texture(uCamera, vUv).rgb, 1.0);
}
"""

  const val BLUR_FRAG = """#version 300 es
precision mediump float;
uniform sampler2D uTex;
uniform vec2 uAxis;
uniform float uWeights[5];
uniform float uOffsets[5];
in highp vec2 vUv;
out vec4 oColor;
void main() {
  vec4 color = texture(uTex, vUv) * uWeights[0];
  for (int i = 1; i < 5; i++) {
    vec2 off = uAxis * uOffsets[i];
    color += texture(uTex, vUv + off) * uWeights[i];
    color += texture(uTex, vUv - off) * uWeights[i];
  }
  oColor = color;
}
"""

  const val TRANSFORM_FRAG = """#version 300 es
precision mediump float;
uniform sampler2D uTex;
uniform mat2 uUvTransform;
in highp vec2 vUv;
out vec4 oColor;
void main() {
  vec2 uv = uUvTransform * (vUv - 0.5) + 0.5;
  oColor = texture(uTex, uv);
}
"""

  const val PLASMA_FRAG = """#version 300 es
precision highp float;

uniform float uTime;       // seconds, monotonically increasing; range [0, inf)
uniform vec2 uResolution;  // framebuffer size in pixels; both components > 0
uniform vec3 uColorA;      // first palette color, linear-ish RGB in [0, 1]
uniform vec3 uColorB;      // second palette color, linear-ish RGB in [0, 1]
uniform float uSpeed;      // animation rate multiplier; 0 freezes the field
uniform float uScale;      // spatial frequency; higher = more, tighter cells

in highp vec2 vUv;
out vec4 oColor;

void main() {
  // Aspect-correct, screen-centered coordinates (matches nebula.frag): divide
  // by the height so uScale reads the same regardless of aspect ratio.
  vec2 fragCoord = vUv * uResolution;
  vec2 uv = (fragCoord - 0.5 * uResolution) / uResolution.y;

  float t = uTime * uSpeed;

  // Classic demoscene plasma: a few sines of position and time. The radial
  // term (length(uv)) gives the field an organic, non-grid-aligned drift.
  float v = sin(uv.x * uScale + t);
  v += sin(uv.y * uScale + t * 0.8);
  v += sin((uv.x + uv.y) * uScale * 0.7 + t * 1.3);
  v += sin(length(uv) * uScale * 1.2 - t);

  // v ranges roughly [-4, 4]; fold through sin to a smooth [0, 1] mix factor.
  float mixT = 0.5 + 0.5 * sin(v);

  // Opaque procedural background; the person is composited over it downstream.
  oColor = vec4(mix(uColorA, uColorB, mixT), 1.0);
}
"""

  // Generative background shaders, by name. The generic shader processor and
  // directory-driven registration iterate this; adding a generative .frag adds
  // an entry here automatically.
  val GENERATIVE: Map<String, String> = mapOf(
    "plasma" to PLASMA_FRAG,
  )
}
