#!/usr/bin/env bun
// Build the Expo config plugin: compile plugin/src -> plugin/build (COMMITTED),
// stamp each output with a "@generated" banner that points back to the source,
// and format with biome so the output is byte-stable. Mirrors build:shaders: a
// generated, committed artifact guarded by a drift gate (check:plugin runs this
// then `git diff --exit-code -- plugin/build`).
//
// tsgo is the Go TypeScript compiler (@typescript/native-preview): same emit as
// tsc, much faster, already the repo's compiler for typecheck/build.

import fs from 'node:fs';
import path from 'node:path';
import { $ } from 'bun';

const ROOT = path.resolve(import.meta.dir, '..');
const PLUGIN_DIR = path.join(ROOT, 'plugin');
const BUILD_DIR = path.join(PLUGIN_DIR, 'build');

const BANNER = `// @generated by \`bun run build:plugin\` — DO NOT EDIT THIS FILE.
// Source of truth: plugin/src/. Edit the TypeScript there, then run
// \`bun run build:plugin\` to regenerate this committed output.
// Committed (not in dist/) because Expo loads the config plugin via
// app.plugin.js -> ./plugin/build at prebuild time, including on EAS workers
// where the library's dist/ and node_modules are absent.`;

// 1. Clean + compile with tsgo.
await $`rm -rf ${BUILD_DIR}`;
await $`tsgo -p ${path.join(PLUGIN_DIR, 'tsconfig.json')}`;

// 2. Stamp the banner onto every emitted .js so a reader (or an LLM) is told
//    where the source lives and how to rebuild, not tempted to edit build/.
const stamp = (dir: string): void => {
  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) stamp(full);
    else if (entry.name.endsWith('.js')) {
      fs.writeFileSync(full, `${BANNER}\n\n${fs.readFileSync(full, 'utf8')}`);
    }
  }
};
stamp(BUILD_DIR);

// 3. Format so rebuilds are byte-identical (the check:plugin drift gate diffs
//    this). Linting is disabled for plugin/build via a biome override; generated
//    code should not answer to lint rules.
await $`biome format --write ${BUILD_DIR}`;

console.log('[build:plugin] compiled plugin/src -> plugin/build');
