// GLSL ES 3.00 source for every web effect's WebGL2 pipeline. Single file so
// "where do I add a new shader on web" has one answer.
//
// Shapes mirror android/.../gpu/Shaders.kt. They are not yet bit-identical
// because the Android side runs on GLES external textures (OES sampler;
// camera buffer arrives transformed) and the web side runs on 2D textures
// (the upstream MediaStreamTrackProcessor already hands us decoded 2D
// frames). The shared structure is: passthrough vertex shader, separable
// 1D Gaussian fragment shader, composite-with-mask fragment shader. Keep
// the math in sync manually for now; extracting to shared .frag files with
// a Metro transformer is a v0.2 conversation.

// Procedural full-screen quad via gl_VertexID; no VAO or VBO required.
// Caller does: gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4).
// Canonical source: shaders/passthrough.vert, code-generated into
// ./shaders.generated by `bun run build:shaders`; re-exported here so web
// imports stay stable.
export { PASSTHROUGH_VERT_SRC } from './shaders.generated';

// Separable 1D Gaussian. uAxis is (1/width, 0) for horizontal, (0, 1/height)
// for vertical. RADIUS is capped at 20 taps per side; uniform sigma controls
// the effective falloff. Taps beyond ~3*sigma contribute ~0 so high RADIUS
// with small sigma is wasteful but visually correct.
export const BLUR_FRAG_SRC = `#version 300 es
precision mediump float;
uniform sampler2D uTex;
uniform vec2 uAxis;
uniform float uSigma;
in highp vec2 vUv;
out vec4 oColor;
const int RADIUS = 20;
void main() {
  float sigma2 = uSigma * uSigma;
  vec4 sum = vec4(0.0);
  float wSum = 0.0;
  for (int i = -RADIUS; i <= RADIUS; i++) {
    float fi = float(i);
    float w = exp(-0.5 * fi * fi / sigma2);
    sum += texture(uTex, vUv + fi * uAxis) * w;
    wSum += w;
  }
  oColor = sum / wSum;
}
`;

// Composite: mix(background, original, mask). One shader, byte-identical
// to android/.../gpu/Shaders.kt's COMPOSITE_FRAG so the same canonical
// GLSL source serves both platforms (and post-transpile, iOS Metal).
//
// uOriginal and uBackground are expected to land with semantic "top of
// source image" at GL v=1; the shader samples both at vUv directly.
// Each platform's host code picks the right upload flag or pre-flip:
//   - Web original / bg: UNPACK_FLIP_Y_WEBGL=true on upload (bg is staged
//     through OffscreenCanvas first since flipY does not apply to
//     ImageBitmap; canvas works).
//   - Android original: OES->2D pass with transformMatrix lands head at v=1.
//   - Android bg: Bitmap pre-flip via Matrix(preScale(1, -1)) before
//     GLUtils.texImage2D, because Android OpenGL ES has no flipY flag.
//
// uMask is parameterized via uMaskUvScale / uMaskUvOffset because we
// cannot canvas-stage the mask on web. Canvas premultiplied-alpha mangles
// the soft confidence values in MediaPipe's segmentationMask alpha
// channel, collapsing the mask to near-binary and breaking the smoothstep
// hardness slider. We therefore direct-upload the mask on web with
// flipY=false and use the uniforms to V-flip the SAMPLING in shader.
// On Android the readback round-trip leaves the mask correctly oriented;
// the uniforms are identity. The uniforms keep the shader byte-identical
// across platforms; per-platform orientation lives in the uniforms.
//
// uBackground is whatever you bind to it: a blurred copy, a sampled PNG,
// or a procedural shader's output. uBgUvScale / uBgUvOffset perform a
// cover-fit center crop when the background's aspect ratio differs from
// the output; the caller computes them from aspect ratios. For a
// full-size background (blur output), pass (1, 1) and (0, 0).
//
// uMaskLo / uMaskHi parameterize the smoothstep transition over the raw
// confidence map; the caller derives them from a hardness factor via
// `maskHardnessRange` in src/web/tuning.ts (mirrors MaskTuning.smoothstepRange
// on Android).
// Canonical source: shaders/composite.frag, code-generated into
// ./shaders.generated by `bun run build:shaders`; re-exported here. The
// per-platform mask/bg orientation differences described above live in the
// uniforms the host sets, not the shader body, so the same generated source
// serves web, Android, and (post-transpile) iOS.
export { COMPOSITE_FRAG_SRC } from './shaders.generated';
