/**
 * Effect specs are parameterized objects. Each effect's shape carries the
 * uniforms its shader needs; the library exposes one shader per effect family
 * (blur, background-image, etc.) and consumers pick uniform values per call.
 */

import type { BackgroundPresetName } from './backgrounds';

/**
 * Geometric reorientation of the frame: an axis flip or a 90-degree rotation.
 * The operation IS the effect name (parameterless), which keeps it compatible
 * with the bare-string input form and the flat-string native registry. On web
 * these run in display space (the reference behavior); native pipelines correct
 * for the camera buffer's rotation so the on-screen result matches everywhere.
 */
export type TransformName = 'flip-x' | 'flip-y' | 'rotate-cw' | 'rotate-ccw';

export type TransformSpec = {
  readonly name: TransformName;
};

export type BlurSpec = {
  readonly name: 'blur';
  /**
   * Gaussian blur sigma (softness); higher = softer. Optional; when omitted
   * the library default applies. Clamped to [0.5, 7] on both native and web.
   *
   * Upstream's `_setVideoEffects(names)` has no argument slot, so this rides
   * the effect-tuning side-channel that already carries uniforms across the
   * bridge: the facade routes it through the Expo Module's tuning function and
   * the per-frame processors read it each frame. The single-active-art-axis
   * model makes a per-call value correct (only one blur is ever active).
   */
  readonly sigma?: number;
};

export type BackgroundImageSpec = {
  readonly name: 'background-image';
  /**
   * Either a bundled preset name (autocompleted; see src/backgrounds.ts) or
   * a free-form URL / data URI. Web accepts both; native only resolves
   * bundled preset names because the upstream rn-webrtc registry takes flat
   * strings, not URIs.
   *
   * The `string & {}` trick preserves preset-name autocomplete while still
   * permitting arbitrary URL inputs without a separate union branch.
   *
   * SECURITY (web): a URL/data-URI `source` is fetched in the page origin and
   * decoded to a texture. If you wire this from end-user input, validate the
   * URL yourself; the library does not allowlist fetch targets. Decoded
   * dimensions are capped and the per-source cache is bounded, but an
   * unvalidated `source` can still issue a same-origin request you did not
   * intend.
   */
  readonly source: BackgroundPresetName | (string & {});
};

/** RGB color, each channel in [0, 1]. */
export type RGB = readonly [number, number, number];

/**
 * Procedural plasma background: a two-color time-morph generated by
 * `shaders/plasma.frag`. The person is composited over it through the
 * segmentation mask, like every art effect. Uniforms are optional; the
 * library fills defaults (an ocean palette). This is the first procedural
 * shader; its uniform shape previews the unified preset contract.
 *
 * Web only for now; native registration lands in a follow-up. On native a
 * `plasma` spec is filtered out (no registered processor yet) rather than
 * crashing.
 */
export type PlasmaSpec = {
  readonly name: 'plasma';
  readonly colorA?: RGB;
  readonly colorB?: RGB;
  readonly speed?: number;
  readonly scale?: number;
};

export type EffectSpec = TransformSpec | BlurSpec | BackgroundImageSpec | PlasmaSpec;

/**
 * Legacy alias for the discriminant. Useful for typed switch statements and
 * the bare-string call shape (`applyVideoEffects(track, ['blur'])`).
 */
export type EffectName = EffectSpec['name'];

/**
 * applyVideoEffects accepts either a bare effect name (no params; library
 * picks sensible defaults) or a full EffectSpec object with parameters.
 */
export type EffectInput = EffectSpec | EffectName;

/**
 * Apply zero or more effects to a local `MediaStreamTrack`.
 *
 * - Native: thin facade over `track._setVideoEffects(names)` from
 *   `react-native-webrtc`. Returns the same track reference; mutation is in place.
 *   Effects are tuned globally via the tuning setters (setBlurSigma, etc.),
 *   not via per-call spec parameters.
 * - Web: builds an Insertable-Streams pipeline with `MediaStreamTrackProcessor`
 *   and `MediaStreamTrackGenerator` and returns a NEW track carrying the
 *   transformed frames. Replace the upstream sender's track with the return value
 *   (`sender.replaceTrack(returnedTrack)`) to apply effects to a peer connection,
 *   or attach it to a `<video>` element for local preview.
 *
 * Throws on remote tracks, unknown effect names, missing platform capabilities
 * (web: Insertable Streams; native: peer-dep `_setVideoEffects`), or non-video
 * tracks.
 */
export type ApplyVideoEffects = (
  track: MediaStreamTrack,
  effects: ReadonlyArray<EffectInput>,
) => MediaStreamTrack;

/**
 * Normalize an EffectInput (bare name or spec) into an EffectSpec.
 */
export const toEffectSpec = (input: EffectInput): EffectSpec =>
  typeof input === 'string' ? ({ name: input } as EffectSpec) : input;
